### ISSUE TITLE
Support the latest open zipkin

### ISSUE THREAD

**Issue by spencergibb** [frodenas/zipkin-boshrelease#1]
From https://bintray.com/openzipkin/zipkin/zipkin/view

/cc @dsyer @adriancole @mstine

**Comment by codefromthecrypt** [comment]
I think @abesto has a final release around the corner! We can start with an
RC, though. https://github.com/openzipkin/zipkin/issues/579

**Comment by frodenas** [comment]
@spencergibb @adriancole If you're not in a hurry, let's wait for the final release. Ping me otherwise and I'll update this release to the latest rc bits.

**Comment by codefromthecrypt** [comment]
should be ready at this point, for version 1.2.2

Here's things I had to do in docker https://github.com/openzipkin/docker-zipkin/pull/25

**Comment by frodenas** [comment]
I just cut [Zipkin BOSH release v3](https://github.com/frodenas/zipkin-boshrelease/releases/tag/v3) that includes Zipkin 1.2.2.

**Comment by codefromthecrypt** [comment]
Cool! I don't have a local bosh setup to verify, but I suspect others do.
I'll start entering commands towards that end, regardless.

**Comment by frodenas** [comment]
I believe @mstine should have one, upgrading it to v3 should be easy, ping me if you need any help.
